"use client";

import { CheckCircle2, Copy, Hourglass, PawPrint, RefreshCw } from "lucide-react";
import { type MouseEvent, type RefObject, useState } from "react";
import Image from "next/image";
import type { ApiWalk } from "../../../../lib/walks";
import { DogmeetDialog, requestDialogClose } from "../../../components/ui/DogmeetFrame";
import type { Pet } from "../model";

type Props = {
  showPetRequired: boolean; informationButtonRef: RefObject<HTMLButtonElement | null>; onContinueToRequiredPet: () => void;
  onDismissPetRequired: () => void;
  showSharedPetAlreadyAdded: boolean; onDismissSharedPetAlreadyAdded: () => void;
  locationRequestSent: boolean; locationRequestButtonRef: RefObject<HTMLButtonElement | null>; onDismissLocationRequestSent: () => void;
  petToShare: Pet | null; petShareLink: string; petShareLoading: boolean; petShareRefreshing: boolean; petShareError: string; petShareCopied: boolean; shareDoneButtonRef: RefObject<HTMLButtonElement | null>; onCopyPetShareLink: () => void; onRotatePetShareLink: (pet: Pet) => void; onClosePetShare: () => void;
  walkPendingDelete: ApiWalk | null; walkDeleting: boolean; walkDeleteError: string;
  petPendingDelete: Pet | null; petDeleting: boolean; petDeleteError: string; deleteCancelRef: RefObject<HTMLButtonElement | null>;
  onDeleteWalk: (event: MouseEvent<HTMLButtonElement>) => void; onCancelDeleteWalk: () => void; onDeletePet: (event: MouseEvent<HTMLButtonElement>) => void; onCancelDeletePet: () => void;
};

export function HomeDialogs(props: Props) {
  const [rotating, setRotating] = useState(false);
  const { showPetRequired, informationButtonRef, onContinueToRequiredPet, showSharedPetAlreadyAdded, onDismissSharedPetAlreadyAdded, locationRequestSent, locationRequestButtonRef, onDismissLocationRequestSent, petToShare, petShareLink, petShareLoading, petShareRefreshing, petShareError, petShareCopied, shareDoneButtonRef, onCopyPetShareLink, onRotatePetShareLink, onClosePetShare, walkPendingDelete, walkDeleting, walkDeleteError, petPendingDelete, petDeleting, petDeleteError, deleteCancelRef, onDeleteWalk, onCancelDeleteWalk, onDeletePet, onCancelDeletePet } = props;
  return <>
    {showPetRequired && <DogmeetDialog className="sheet--pet-required" aria-label="Сначала питомец" onDismiss={props.onDismissPetRequired}><PawPrint className="state-icon" /><h2>Познакомимся<br />с питомцем?</h2><p>Добавьте питомца, чтобы соседи знали, с кем вы выйдете гулять.</p><button ref={informationButtonRef} className="button" type="button" onClick={(event) => requestDialogClose(event.currentTarget, onContinueToRequiredPet)}>Добавить питомца</button><button className="button quiet" type="button" onClick={(event) => requestDialogClose(event.currentTarget, props.onDismissPetRequired)}>Пока посмотреть прогулки</button></DogmeetDialog>}
    {showSharedPetAlreadyAdded && <DogmeetDialog title="Питомец уже добавлен" role="alertdialog" onDismiss={onDismissSharedPetAlreadyAdded}><CheckCircle2 className="state-icon" /><h2 id="already-title">Вы уже знакомы</h2><p>Этот питомец уже есть в вашем списке. Добавлять его снова не нужно.</p><button className="button" type="button" onClick={(event) => requestDialogClose(event.currentTarget, onDismissSharedPetAlreadyAdded)}>К моим питомцам</button></DogmeetDialog>}
    {locationRequestSent && <DogmeetDialog className="sheet--location-sent" title="Новая локация" onDismiss={onDismissLocationRequestSent}><Hourglass className="state-icon" /><h2 id="location-sent-title">Заявка отправлена</h2><p>Пока мы рассматриваем заявку, можно выбрать соседний жилой комплекс.</p><button ref={locationRequestButtonRef} className="button" type="button" onClick={(event) => requestDialogClose(event.currentTarget, onDismissLocationRequestSent)}>Хорошо</button></DogmeetDialog>}
    {petToShare && <DogmeetDialog className={rotating ? "" : "sheet--share"} title={rotating ? "Обновить ссылку" : undefined} aria-label="Поделиться питомцем" busy={petShareRefreshing} onDismiss={() => { if (rotating) setRotating(false); else onClosePetShare(); }}>{rotating ? <><RefreshCw className="state-icon" /><h2>Заменить ссылку?</h2><p>Старая ссылка перестанет действовать. Доступ тех, кто уже добавил питомца, сохранится.</p>{petShareError && <p className="field-error" role="alert">{petShareError}</p>}<button type="button" className="button" disabled={petShareRefreshing} onClick={() => { onRotatePetShareLink(petToShare); setRotating(false); }}>Получить новую ссылку</button><button type="button" className="button quiet" onClick={() => setRotating(false)}>Сохранить прежнюю</button></> : <><h2 id="pet-share-title">Один питомец.<br />Общие планы.</h2><p>Передайте ссылку близкому человеку: он сможет управлять питомцем {petToShare.name} и сообщать о прогулках.</p>{petShareLoading ? <div className="resource-loading" role="status"><span /><span className="short" /></div> : <><label className="field"><span>Одноразовая ссылка</span><input readOnly value={petShareLink} onFocus={(event) => event.currentTarget.select()} /></label><button className="button" type="button" disabled={!petShareLink} onClick={onCopyPetShareLink}>{petShareCopied ? <CheckCircle2 /> : <Copy />} {petShareCopied ? "Скопировано" : "Скопировать ссылку"}</button><p className="small-note">Ссылка действует для одного добавления.</p><button className="button quiet" type="button" disabled={!petShareLink || petShareRefreshing} onClick={() => setRotating(true)}><RefreshCw />{petShareRefreshing ? "Обновляем…" : "Получить новую ссылку"}</button></>}{petShareError && <p className="field-error" role="alert">{petShareError}</p>}<button ref={shareDoneButtonRef} className="visually-hidden" type="button" onClick={(event) => requestDialogClose(event.currentTarget, onClosePetShare)}>Закрыть</button></>}</DogmeetDialog>}
    {walkPendingDelete && <DogmeetDialog title="Удалить прогулку?" role="alertdialog" busy={walkDeleting} onDismiss={onCancelDeleteWalk}><p>Прогулка в {walkPendingDelete.walkTime.slice(0, 5)}, {walkPendingDelete.point.toLowerCase()}, исчезнет из расписания.</p><p>Добавьте новую, когда снова соберётесь гулять.</p>{walkDeleteError && <p className="field-error" role="alert">{walkDeleteError}</p>}<button className="button danger" type="button" disabled={walkDeleting} onClick={onDeleteWalk}>{walkDeleting ? "Удаляем…" : "Удалить прогулку"}</button><button ref={deleteCancelRef} className="button quiet" type="button" disabled={walkDeleting} onClick={(event) => requestDialogClose(event.currentTarget, onCancelDeleteWalk)}>Оставить</button></DogmeetDialog>}
    {petPendingDelete && <DogmeetDialog title="Удалить питомца" role="alertdialog" busy={petDeleting} onDismiss={onCancelDeletePet}><Image className="pet-face large" src={petPendingDelete.photoUrl} alt={petPendingDelete.name} width={92} height={92} unoptimized /><h2 id="delete-pet-title">{petPendingDelete.isOwner ? `Удалить ${petPendingDelete.name}?` : "Убрать из списка?"}</h2><p>{petPendingDelete.isOwner ? "Питомец и все его прогулки будут удалены. Это действие нельзя отменить." : "Питомец исчезнет только из вашего списка. У владельца он останется."}</p>{petDeleteError && <p className="field-error" role="alert">{petDeleteError}</p>}<button className="button danger" type="button" disabled={petDeleting} onClick={onDeletePet}>{petDeleting ? "Удаляем…" : petPendingDelete.isOwner ? "Удалить питомца" : "Убрать из списка"}</button><button ref={deleteCancelRef} className="button quiet" type="button" disabled={petDeleting} onClick={(event) => requestDialogClose(event.currentTarget, onCancelDeletePet)}>Оставить</button></DogmeetDialog>}
  </>;
}
